### PR TITLE
fix performance regression calling IO.select for every packet

### LINKED ISSUE #21: bad read performance since shutdown refactor
From my experiments today, using IO.select + nonblocking rcvm_from makes the plugin half as fast as before. In my machine I can see around 17keps with nonblocking io, but 40keps with a blocking read.

The difference is:

#### slower

```ruby
   while !stop?
      next if IO.select([@udp], [], [], 0.5).nil?
      payload, client = @udp.recvfrom_nonblock(@buffer_size)
      next if payload.empty?
      @input_to_worker.push([payload, client])
    end
```

#### faster

```ruby
   while !stop?
      payload, client = @udp.recvfrom(@buffer_size)
      @input_to_worker.push([payload, client])
    end
```

The obvious downside is that the faster solution makes the plugin non interruptible if no data is coming, since recvfrom is blocking..thoughts?

### PR DESCRIPTION
**Pull request by IrlJidel**
Fixes #21 

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by clintongormley** [comment]
@jsvd the CLA is now signed

**Comment by jsvd** [comment]
I will do a small amount of manual testing today or tomorrow morning and if all's good I'll merge it tomorrow.
Thanks for the work @IrlJidel :)

**Comment by IrlJidel** [comment]
jsvd@ Any issues found duringtesting?

**Comment by jsvd** [comment]
@IrlJidel awesome PR, nice speed boost (14k eps to 24k eps on my laptop) and all seems good 👍 
LGTM

**Comment by jsvd** [comment]
Version 3.0.3 has been released with this patch :+1:

**Pull request closed without merging**
